### ISSUE TITLE
Feature Request: Dynamically change settings

### ISSUE THREAD

**Issue by sbarwe** [DeanCording/node-red-contrib-config#2]
Hi Dean,

your node is great for setting up context space.

With the new feature to reapply settings, the following features would be great:

- overwrite config values by msg (e.g. msg = { topic: "update", payload:{ flow:{ key1:"value", key2:"value2" }, global: { keyX: 20 } })

- provide method to store  config (deploy) --> will provide persistence for flow/global context
(e.g. msg = { topic: "commit", payload:{ flow:{ key1:"value", key2:"value2" }, global: { keyX: 20 } })

- provide config setting (Checkbox) to persist current config values on runtime shutdown ("close" )

br
Seb

PS: you may checkout node-red-contrib-contextbrowser  - builds a great team together with node-red-contrib-config

**Comment by DeanCording** [comment]
Hi Seb,

Shouldn't be too hard to make save and restore nodes.  Let me have a think about it.

Dean

**Comment by DeanCording** [comment]
It's taken a while but I've finally had a chance to revisit this code.

**Overwrite config values**
I'm not sure I can see any purpose for this that wouldn't be served by just using the Change node.  Dynamically changing alternate configurations maybe?  

**Store Config**
Actually this is outside of the scope of the Config node.  Persisting flow and global context is a useful thing to have for saving 'blackboard memory' between restarts.  Probably best to have a separate node though.

**Persist  current config settings**
This can be accomplished by using the node-red-contrib-persist node to save the last trigger message and replay it at startup.     As to whether this would be useful, I'm not so sure and it could definitely result in some obscure behaviours that can't be cleared by restarting into a know state.

One of the issues is that start up and shutdown sequencing of nodes is very indeterminate. It is impossible to specify or even determine in what order things occur.


Anyhow, I've put node-red-contrib-context-persist on my to-do list.

Dean
