### ISSUE TITLE
Config node seemingly broken in Node-RED v1.0.0 betas?

### ISSUE THREAD

**Issue by dudleyjosh** [DeanCording/node-red-contrib-config#4]
I've been playing with the Node-RED v1.0.0 betas recently and this config node seems to be broken for those versions.

**Comment by zieherf** [comment]
Still broken on Node-RED v1.0.0 final release. Are there any plans to fix that? Would appreciate if this could be resolved.

**Comment by ryanrdetzel** [comment]
I added some context here, not sure why it's broken though.

https://discourse.nodered.org/t/1-0-causing-issue-with-pallet/16176

**Comment by StephanStS** [comment]
@dudleyjosh, @zieherf: Did you perform a test with the actual NR version (e.g. v1.0.5)?
At my installation all is working fine, but I did never use the node with an older NR release.
You can easily use the example added at the end of the [README.md file](https://github.com/DeanCording/node-red-contrib-config/blob/master/README.md). 
If it works, I would like to close this issue.

Regards
Stephan

**Comment by dudleyjosh** [comment]
I haven't tested it but you can close this issue... I just use the inject node with a change node for this purpose now.

**Comment by StephanStS** [comment]
@dudleyjosh, @DeanCording: Could somebody of you please close the issue?
